version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ros-cicd"
s3_bucket = "<YOUR_BUCKET>"
s3_prefix = "cicd"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

